version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  postgres-data:
  elasticsearch-data:
